#! /usr/bin/env bash
#
# Author: Maharishi Bhatia

declare -A commands

commands[sizedf]=../commands/sizedf
commands[cputemp]=../commands/cputemp
commands[lscpu]=../commands/lscpu
commands[pubip]=../commands/pubip
commands[killnet]=../commands/killnet
commands[spurnet]=../commands/spurnet

export commands

exists(){
    if [ ! -v ${commands[$1]} ]; then
        echo 0
    fi
}