#!/bin/bash

echo "Starting Install"

echo
echo "APT updating"
sudo apt update

echo
echo "Installing Latest Version of Dependant binaries & libraries"
sudo apt install -y jq #JSON manipulation library

# Only if you want to install mqtt server, if you have an existing one you can use that server
# sudo apt-get install -y mosquitto

sudo apt-get install -y mosquitto-clients #MQTT publisher and subscriber

echo
echo "Stopping Existiong Service"
sudo systemctl stop serverbot.service
sudo systemctl stop serverbot.timer
sudo systemctl stop clientbot.service

cd ..
echo
echo "Copying Latest changes"
sudo cp -vrf ./pibot/* /srv/pibot/

echo
echo "Setting up the systemctl"
cd /etc/systemd/system/ || exit
sudo ln -s /srv/pibot/server/serverbot.service serverbot.service ||
sudo ln -s /srv/pibot/server/serverbot.timer serverbot.timer ||
sudo ln -s /srv/pibot/client/clientbot.service clientbot.service ||

cd /srv/pibot || exit

echo
echo "Reenabling & restarting systemctl"
sudo systemctl daemon-reload
sudo systemctl enable serverbot.service
sudo systemctl enable serverbot.timer
sudo systemctl start serverbot.service
sudo systemctl start serverbot.timer
sudo systemctl enable clientbot.service
sudo systemctl start clientbot.service

echo
echo "Install Complete"


