# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MQTT_SERVER: ${{ secrets.MQTT_SERVER }}
          BASE_TELEGRAM_URL: ${{ secrets.BASE_TELEGRAM_URL }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Creating the .secure file

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo export BOT_TOKEN=$BOT_TOKEN > ${{ github.workspace }}/.secure
          echo export CHAT_ID=$CHAT_ID >> ${{ github.workspace }}/.secure,
          echo export MQTT_SERVER=$MQTT_SERVER >> ${{ github.workspace }}/.secure,
          echo export BASE_TELEGRAM_URL=$BASE_TELEGRAM_URL >> ${{ github.workspace }}/.secure,
          
