# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MQTT_SERVER: ${{ secrets.MQTT_SERVER }}
          BASE_TELEGRAM_URL: ${{ secrets.BASE_TELEGRAM_URL }}

      # Runs a set of commands using the runners shell
      - name: Creating the .secure file
        run: |
          echo "Setting up the secured file"
          {
              echo "#!/usr/bin/env bash"
              echo export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
              echo export CHAT_ID=${{ secrets.CHAT_ID }}
              echo export MQTT_SERVER=${{ secrets.MQTT_SERVER }}
              echo export BASE_TELEGRAM_URL=${{ secrets.BASE_TELEGRAM_URL }}
          } >> ${{ github.workspace }}/.secure
          chmod +x ${{ github.workspace }}/.secure
      
      # Runs a single command using the runners shell
      - name: Installs the product on the server
        run: ${{ github.workspace }}/install
      
